// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxy507GnesmRiN-NnUv1MlEdCWvJ3Yv4',
    appId: '1:852330392434:web:03b6e9699039c2f9e7cbeb',
    messagingSenderId: '852330392434',
    projectId: 'attendance-app-manual',
    authDomain: 'attendance-app-manual.firebaseapp.com',
    storageBucket: 'attendance-app-manual.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAD_KSS5aoudHl4Qonw3WnHpp5gE1Ch7g',
    appId: '1:852330392434:android:a4758898d2d59a0ee7cbeb',
    messagingSenderId: '852330392434',
    projectId: 'attendance-app-manual',
    storageBucket: 'attendance-app-manual.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqB_hyHK6nZHWhGGMvtNU8AYfadt2W_BM',
    appId: '1:639373845940:ios:247e681abb1b6a887f3ee1',
    messagingSenderId: '639373845940',
    projectId: 'attendance-app-6638e',
    storageBucket: 'attendance-app-6638e.firebasestorage.app',
    iosBundleId: 'com.example.attend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqB_hyHK6nZHWhGGMvtNU8AYfadt2W_BM',
    appId: '1:639373845940:ios:247e681abb1b6a887f3ee1',
    messagingSenderId: '639373845940',
    projectId: 'attendance-app-6638e',
    storageBucket: 'attendance-app-6638e.firebasestorage.app',
    iosBundleId: 'com.example.attend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqj_gXZeTpsNcnAo-o6yilH8wV3afTnoc',
    appId: '1:639373845940:web:d76bb982e0e143637f3ee1',
    messagingSenderId: '639373845940',
    projectId: 'attendance-app-6638e',
    authDomain: 'attendance-app-6638e.firebaseapp.com',
    storageBucket: 'attendance-app-6638e.firebasestorage.app',
    measurementId: 'G-4F7SDRR9FH',
  );
}
